import { session } from "@/utils/utils";
export default [
    {
        path: "pay",
        name: "WebPay",
        component: () => import("@/views/zhifu/zhifu.vue"),
        meta: { authLogin: true },
    },
    {
        path: "yisheng",
        name: "IndexyishengList",
        component: () => import("@/views/yisheng/index.vue"),
        meta: { title: "医生列表" },
    },
    {
        path: "yisheng/detail",
        name: "IndexyishengDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yisheng/detail-web.vue"),
        meta: { title: "医生详情" },
    },
    {
        path: "paiban/detail",
        name: "IndexpaibanDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/paiban/detail-web.vue"),
        meta: { title: "排班详情" },
    },
    {
        path: "yuyueguahao/add",
        name: "IndexyuyueguahaoAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yuyueguahao/add-web.vue"),
        meta: { title: "预约挂号添加", authLogin: true, msg: true },
    },
    {
        path: "yonghu",
        name: "IndexyonghuList",
        component: () => import("@/views/yonghu/index.vue"),
        meta: { title: "用户列表" },
    },
    {
        path: "yonghu/add",
        name: "IndexyonghuAdd",
        component: () => import("@/views/yonghu/add-web.vue"),
        meta: { title: "用户添加" },
    },
    {
        path: "yonghu/detail",
        name: "IndexyonghuDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/detail-web.vue"),
        meta: { title: "用户详情" },
    },
    {
        path: "shijuan",
        name: "IndexshijuanList",
        component: () => import("@/views/shijuan/index.vue"),
        meta: { title: "试卷列表" },
    },
    {
        path: "shijuan/detail",
        name: "IndexshijuanDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shijuan/detail-web.vue"),
        meta: { title: "试卷详情" },
    },
    {
        path: "wenzhang",
        name: "IndexwenzhangList",
        component: () => import("@/views/wenzhang/index.vue"),
        meta: { title: "文章列表" },
    },
    {
        path: "wenzhang/detail",
        name: "IndexwenzhangDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/wenzhang/detail-web.vue"),
        meta: { title: "文章详情" },
    },
    {
        path: "liuyanban/add",
        name: "IndexliuyanbanAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/liuyanban/add-web.vue"),
        meta: { title: "留言板添加", authLogin: true, msg: true },
    },
    {
        path: "yaopin",
        name: "IndexyaopinList",
        component: () => import("@/views/yaopin/index.vue"),
        meta: { title: "药品列表" },
    },
    {
        path: "yaopin/detail",
        name: "IndexyaopinDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yaopin/detail-web.vue"),
        meta: { title: "药品详情" },
    },
    {
        path: "gouwuche",
        name: "IndexgouwucheList",
        component: () => import("@/views/gouwuche/index.vue"),
        meta: { title: "购物车列表", authLogin: true, msg: true },
    },
    {
        path: "gouwuche/add",
        name: "IndexgouwucheAdd",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/gouwuche/add-web.vue"),
        meta: { title: "购物车添加", authLogin: true, msg: true },
    },
    {
        path: "dingdan",
        name: "IndexdingdanList",
        component: () => import("@/views/dingdan/index.vue"),
        meta: { title: "订单列表", authLogin: true, msg: true },
    },
    {
        path: "dingdan/add",
        name: "IndexdingdanAdd",
        component: () => import("@/views/dingdan/add-web.vue"),
        meta: { title: "订单添加", authLogin: true, msg: true },
    },
];
